import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link"; 

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`} 
      style={{ backgroundImage: "url('https://wallpaperkenya.co.ke/wp-content/uploads/2022/05/minimal-morning-landscape-8k-gx-scaled.jpg')", 
      backgroundSize: 'cover', backgroundPosition: 'center', backgroundRepeat: 'no-repeat' }}>

        <div className={styles.description}>
          <div>
            
              <span>Welcome!</span>
            
          </div>
        </div>

        <div className={styles.center}></div>

        <div className={styles.grid}>
          <Link href="/page1" className={styles.card}>
            <div>
              <h2>Page1 <span>-&gt;</span></h2>
              <p>This is page&nbsp;1</p>
            </div>
          </Link>

          <Link href="/page2" className={styles.card}>
            <div>
              <h2>Page2 <span>-&gt;</span></h2>
              <p>This is page&nbsp;2</p>
            </div>
          </Link>

          <Link href="/page3" className={styles.card}>
            <div>
              <h2>Page3 <span>-&gt;</span></h2>
              <p>This is page&nbsp;3</p>
            </div>
          </Link>

          <Link href="/page4" className={styles.card}>
            <div>
              <h2>Page4 <span>-&gt;</span></h2>
              <p>This is page&nbsp;4</p>
            </div>
          </Link>

          <Link href="/page5" className={styles.card}>
            <div>
              <h2>Page5 <span>-&gt;</span></h2>
              <p>This is page&nbsp;5</p>
            </div>
          </Link>

          <Link href="/page6" className={styles.card}>
            <div>
              <h2>Page6 <span>-&gt;</span></h2>
              <p>This is page&nbsp;6</p>
            </div>
          </Link>
        </div>
      </main>
    </>
  );
}
